_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    BOX_QUALITY: "iou"
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT_DIR: "output/fcos/MS_R_101_2x_iou"
