_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/resnet18_w32a32.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  FCOS:
    NORM: "SyncBN"
  # open the mix precision if GPU memory not enough. Known issue: fp16 conflicts with SyncBN for multi GPU training
  #fp16: True
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R_18_1x-Full-SyncBN"
