# This is a basic workflow to help you get started with Actions

name: auto-merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'master'

    # Runs a set of commands using the runners shell
    - name: Run update master from upstream
      run: |
        echo Merge upstream
        git config --global user.name 'blueardour'
        git config --global user.email 'blueardour@gmail.com'
        git pull --unshallow
        git remote add upstream https://github.com/aim-uofa/AdelaiDet
        git remote -v
        git status        
        git fetch upstream
        git merge --no-edit upstream/master
        git push origin master
        git status
        
        
